fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.13.1"
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
      ref: "2.0.0"
    cron_core:
      repo: "puppetlabs/cron_core"
      ref: "1.0.2"
